### ISSUE TITLE
Can't get %ressdead to work

### ISSUE THREAD

**Issue by modhunter** [MrTheSoulz/NerdPack#40]
When using it such as: `{ "%ressdead('Resuscitate')" },` I can't seem to get this to work and need to manually cast Resuscitate, which is fine.

I wonder if `local spell = spellResolve(args, Obj.key, false)` is at issue?  We're passing in the spell as the first argument but it looks like this is getting overrwritten by the result of the call to spellResolve.  Should the spellResolve call change to actually use the spell passed into ressdead?

```
  ['ressdead'] = function(spell, target, sI, args)
    for i=1,#NeP.OM.unitFriend do
      local Obj = NeP.OM.unitFriend[i]
      local spell = spellResolve(args, Obj.key, false)
      if spell and Obj.distance < 40 and UnitIsPlayer(Obj.Key)
      and UnitIsDeadOrGhost(Obj.key) and UnitPlayerOrPetInParty(Obj.key) then
        if sI then SpellStopCasting() end
        Cast(spell, Obj.key, false)
        return true
      end
    end
  end,
```

**Comment by MrTheSoulz** [comment]
spellResolve is need to verify if we actualy have it and convert to name, etc...
Will look into why is failing

**Comment by modhunter** [comment]
We're wiping the OM (and list of dead units) every .25s.  And subsequently re-adding them via `NeP.OM.addToOM`.  Maybe there is some sort of race condition at play here?

**Comment by MrTheSoulz** [comment]
Good point, will investigate

**Comment by MrTheSoulz** [comment]
ive made the necessary changes so that dosent happens

**Comment by MrTheSoulz** [comment]
Its %ressdead(SPELL)
Forgot to mention, sorry

**Comment by modhunter** [comment]
Like "%ressdead('spell')"` or `"%ressdead(spell)"` ?

**Comment by MrTheSoulz** [comment]
"%ressdead(spell)"

**Comment by macedoniazxv** [comment]
fixed? Its work?

**Comment by MrTheSoulz** [comment]
untested, should be tho.

**Comment by modhunter** [comment]
I've not been able to get this to work after combat is over in a dungeon run but would like confirmation from others.  I'm using it as follows in the out of combat section:

`{ "%ressdead('Resuscitate')", (function() return F('auto_res') end) },`

**Comment by modhunter** [comment]
This was closed, but the following still does not work - tested in a raid last night.  After combat there were two dead people and it didn't do anything:

(this is in the out of combat' section:
`{ "%ressdead(Resuscitate)", 'UI(auto_res)' },`

Does the spell name need quotes around it?

**Comment by vorus** [comment]
@modhunter This may have been related to #164 which has been closed.

**Comment by modhunter** [comment]
@Yobleed and I are still not able to make this one work even after the changes - has anyone been able to make this work?

**Comment by Yobleed** [comment]
nope not working
